M48
; DRILL file KiCad 10.0.4 date 2026-08-10T15:34:50
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-08-10T15:34:50-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X1.8508Y-1.8955
X2.0783Y-1.8955
T2
X2.4862Y-2.0965
X2.4862Y-2.2146
M30
